import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


import { Toaster } from "@/components/ui/toaster"
import Navbar from "@/components/Navbar";
// import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "bsp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <SessionWrapper>
    <>
    {/* <Navbar/> */}
      <html lang="en">
        <body className={inter.className + " min-h-screen"}>
          
            {children}
            <Toaster />
        </body>
      </html>
      </>
    // </SessionWrapper>
  );
}
